drop table if exists bookmarks;

CREATE TABLE bookmarks (
	id integer NULL GENERATED BY DEFAULT AS IDENTITY,
	title text NOT NULL,
	url varchar NOT NULL,
	rating integer NOT NULL,
	description text NULL,
	CONSTRAINT bookmarks_pk PRIMARY KEY (id)
	--CONSTRAINT bookmarks_check CHECK (rating > 0 AND rating < 5 IS NULL)
);

insert into public.bookmarks (title, url, rating, description)
values
    ('Google', 'http://www.google.com', '3', 'Internet-related services and products.'),
    ('Thinkful', 'http://www.thinkful.com', '5', '1-on-1 learning to accelerate your way to a new high-growth tech career!'),
    ('Github', 'http://www.github.com', '4', 'brings together the world''s largest community of developers.'),
    ('Steve', 'http://www.steveisawesome.com', '5', 'One awesome guy'),
    ('AntiGoogle', 'http://www.elgooG.com', '1', 'elgoog it. I dare you'),
    ('Amy Zon', 'http://www.amyzon.com', '3', 'Get Amy Zon Prime for 19.95'),
    ('ATI', 'http://www.againsttheinternet.org', '2', 'A website devoted to stopping all websites and ending the internet''s tyrany'),
    ('JustAnotherWebsite', 'http://www.jawjawjaw.com', '4', 'A website used to fill in data'),
    ('Thatguy', 'http://wwww.thatguy->.com', '1', 'Aw website devoted to that guy. You know who I mean.'),
    ('FeedMe', 'http://wwww.feedme.com', '3', 'Devoted to videos of people eating');